name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # 手动触发配置
    inputs:
      arch:  # 架构选择参数
        description: 'Select target architecture'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - x86
          - x86_64
          - arm64-v8a
          - armeabi-v7a

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        ndk-version: '25c'

    - name: Set NDK path
      run: echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/$ANDROID_NDK_VERSION" >> $GITHUB_ENV

    - name: Grant execute permissions
      run: chmod +x ./gradlew

    - name: Build architecture(s)
      run: |
        if [ "${{ github.event.inputs.arch }}" == "all" ]; then
          ./gradlew assembleDebug
        else
          ./gradlew assemble${{ github.event.inputs.arch.toUpperCase() }}Debug
        fi

    - name: Upload APK artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android-apk-${{ github.event.inputs.arch }}
        path: app/build/outputs/apk/**/debug/*.apk
